# Generated by Django 2.2.11 on 2020-03-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
    ]
