# Generated by Django 2.2.11 on 2020-03-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200329_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ebook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tile', models.CharField(max_length=20, unique=True)),
                ('pub_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('publish', models.CharField(max_length=32)),
            ],
        ),
    ]
